[language]
rust = ["rustc +stable"]
python = [
    "python3.7",
    "python3.8",
    "python3.9",
    "python3.10",
    "python3.11",
    "python3.12",
    "python3.13"
]

[langversion]
c = ["", "c89", "c90", "c99", "c11", "c17"]
cpp = ["", "c++98", "c++03", "c++11", "c++14", "c++17", "c++20", "c++23"]
