name: Simple

on:
  [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          g++ --version
          go version
      - uses: dtolnay/rust-toolchain@stable
      - uses: julia-actions/setup-julia@v2
      - uses: jorelali/setup-elm@v6
      - uses: actions/setup-python@v5
        with:
          # NOTE: Github actions doesn't support 3.6 and older.
          python-version: |
            3.7
            3.13
      - run: bash scripts/run.sh
